config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'profile', to: 'users#show', as: 'user_profile' # Define the user profile route
  end

  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  # resources :tweets
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get 'tweets/hashtag/:hashtag', to: 'tweets#tweets_by_hashtag', as: 'tweets_by_hashtag'
  # resources :users
  resources :session
  resources :tweets
  resources :hashtags
  resources :mentions

  # resources :users do
  #   resources :tweets
  # end
  root :to => "tweets#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
    has_and_belongs_to_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags
  has_and_belongs_to_many :mentions, class_name: 'User', join_table: 'mentions_tweets'

  validates :content, presence: true

  after_save :extract_hashtags_and_mentions
  def extract_hashtags_and_mentions
    self.hashtags = content.scan(/#\w+/).map { |name| Hashtag.find_or_create_by(name: name.downcase) }
    self.mentions = content.scan(/@(\w+)/).map { |name| User.find_by(name: name) }.compact
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if !@user
    flash.now.alert = "Username #{params[:name]} was invalid"
    render :new
    elsif @user.password == params[:password]
    session[:user] = @user.name
    redirect_to root_url, notice: "Logged in!"
    else
    flash.now.alert = "The password is invalid"
    render :new
    end

  end

  def destroy
    session[:user] = nil
    redirect_to root_url, notice: "Logged out!"

  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  def tweets_by_hashtag
    @tweets = Tweet.includes(:hashtags).where(hashtags: { name: '#'+ params[:hashtag] })
  end

  # GET /tweets or /tweets.json
  def index
    if params[:hashtag]
      hashtag = Hashtag.find_by(name: params[:hashtag])
      @tweets = hashtag ? hashtag.tweets : []
    else
      @tweets = Tweet.all
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    if !session[:user]
      redirect_to tweets_path, :notice => "You have to log in to
      create a new tweet "
      else
      @tweet = Tweet.new
      end
      
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
    if @tweet.user.name != session[:user]
    redirect_to tweets_path, :alert => "You cannot edit another
    user’s tweet!"
    else
    @tweet = Tweet.find(params[:id])
    end
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = User.find_by name: session[:user]


    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    if @tweet.user.name != session[:user]
      redirect_to tweets_path, :notice => "You cannot delete
      another user’s tweet!"
      else
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:text, :user_id, :content, :mentions, :hashtags)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: "Signed up! You can now log in."  }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def linkify_mentions(content)
        return unless content.present?

        content.gsub(/@(\w+)/) do |match|
            mention = $1
            user = User.find_by(name: mention)
            if user
                link_to match, user_path(user)
            else
                match
            end
        end.gsub(/(#\w+)/) do |match|
            hashtag = $1
            link_to match, tweets_by_hashtag_path(hashtag[1..])
        end.html_safe
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Tweeter</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'dataturbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinkstrack' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
 <div id="container">
 <div class="user_nav">
 <% if session[:user] %>
 Logged in as <%= session[:user] %>.
 <%= link_to "Log out", logout_path %>
 <% else %>
 <%= link_to "Sign up", signup_path %> or
 <%= link_to "log in", login_path %>.
 <% end %>
 </div>
 <%= yield %>
 </div>
</body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<%= form_tag("/login", method: "post") do %>
<div class="field">
<%= label_tag :name %>
<%= text_field_tag :name, params[:name] %>
</div>
<div class="field">
<%= label_tag :password%>
<%= password_field_tag :password, params[:password] %>
</div>
<div class="actions">
<%= submit_tag "Log in"%>
</div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@tweet.errors.count, "error") %> prohibited
this tweet from being
saved:</h2>
<ul>
<% @tweet.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<%= f.label :content %><br>
<%= f.text_field :content %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Text:</strong>
    <%= tweet.text %>
  </p>
  <p>
    <strong>Content:</strong>
    <%= tweet.content %>
  </p>
  <p>
    <strong>User:</strong>
    <%= tweet.user_id %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Tweets</h1>
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.user.name %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<strong>Content:</strong>
<%= linkify_mentions(@tweet.content) %>
</p>
<p>
<strong>User:</strong>
<%= @tweet.user.name %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>
<%= button_to "Destroy this tweet", @tweet, method: :delete %>

app/views/tweets/tweets_by_hashtag.html.erb
<h1>Tweets with Hashtag #<%= params[:hashtag] %></h1>

<% @tweets.each do |tweet| %>
  <div>
    <hr/>
    <p><%=linkify_mentions(tweet.content)%></p>
    <b><td>Posted at: <%= tweet.created_at %></td></b>
    <br/>
    <b><td>by: <%= linkify_mentions('@' + tweet.user.name) %></td></b>
    <!-- Display other tweet information as needed -->
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @user  %> 

<h2> <td>Username: <%= @user.name %></td></h2>
<% @user.tweets.each do |tweet| %>
  <tr>
    <hr/>
      <td><%= linkify_mentions(tweet.content) %></td>
      <br/>
      <b><td>Posted at: <%= tweet.created_at %></td></b>
      <br/>
      <b><td>by: <%= linkify_mentions('@' + tweet.user.name) %></td></b>
    </tr>
<% end %>
<hr/>
<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>